[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200

lib_deps =
    links2004/WebSockets
    pololu/LSM303
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
board_build.filesystem = littlefs