[env:compass_test]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -D VERSION=LSM_V3.0
    -D LSM_V3

monitor_speed = 115200
monitor_port = COM41

lib_deps =
    links2004/WebSockets
    pololu/LSM303
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
    bblanchon/ArduinoJson
board_build.filesystem = littlefs

upload_protocol = espota
upload_port = 192.168.137.26
