#ifndef ROBOBOBUOYVERSION_H_
#define ROBOBOBUOYVERSION_H_

#define PROJECT BOBOBUOY
#define TOPVERSION 3.0
#define SUBVERSION 3.0
#define LORAVERSION 3.0
#define CONTROLVERSION 3.0

#endif /* ROBOBOBUOYVERSION_H_ */
