[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
board_build.partitions = default_8MB.csv

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ICM20X @ ^2.0.7
    adafruit/Adafruit BusIO @ ^1.15.0
    mathieucarbou/ESPAsyncWebServer @ ^3.1.1
    bblanchon/ArduinoJson @ ^7.0.4
