#ifndef ROBOBOBUOYVERSION_H_
#define ROBOBOBUOYVERSION_H_

#define PROJECT BOBOBUOY
#define TOPVERSION 4.0
#define SUBVERSION 4.0
#define LORAVERSION 4.0
#define CONTROLVERSION 4.0

#endif /* ROBOBOBUOYVERSION_H_ */
