; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wireless_tracker]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Upload configurations (connected to COM11)
upload_port = COM11
upload_speed = 921600
monitor_port = COM11
monitor_speed = 115200

; Build flags for Heltec Wireless Tracker ESP32-S3
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

; Library Dependencies
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library @ ^1.3.2
    stm32duino/STM32duino LSM303AGR @ ^2.0.2
