#ifndef COMMANDS_H_
#define COMMANDS_H_

/*
    [Designator][Reciever][MSG_ID][lengt_msg][msg]
*/

typedef enum
{
    POSITION = 1,
    GET_POSITION,

    BATTERY_LEVEL,
    GET_BATTERY_LEVEL,

    BUOY_MODE,
    SET_BUOY_MODE,
    GET_BUOY_MODE,

    DOC_POSITION,
    SET_DOC_POSITION,
    GET_DOC_POSITION,
    GOTO_DOC_POSITION,

    BUOY_ID,
    SET_BUOY_ID,
    GET_BUOY_ID,

    ANCHOR_POSITION,
    SET_ANGHOR_POSITION,
    GET_ANGHOR_POSITION,

    TARGET_POSITION,
    SET_TARGET_POSITION,
    GET_TARGET_POSITION,

    GET_DIR_DISTANSE_ANCHOR_POSITION,
    SET_ANCHOR_POSITION_AS_TARGET_POSITION,
    SET_CURREND_POSITION_AS_ANCHOR_POSITION,

    DIR_DISTANSE_TO_TARGET_POSITION,
    GET_DIR_DISTANSE_TARGET_POSITION,
    DIR_DISTANSE_SPEED_SBSPPEED_BBSPEED_TARGET_POSITION,
    GET_DIR_DISTANSE_SBSPPEED_BBSPEED_TARGET_POSITION,

    SAIL_DIR_SPEED,
    SET_SAIL_DIR_SPEED,
    GET_SAIL_DIR_SPEED,
    SET_SAIL_SPEED,
    SET_SAIL_DIR,
    SET_SBPWR_BBPWR,

    SET_SAIL_TO_DOC_POSITION,
    SET_BUOY_MODE_IDLE,

    SYSTEM_STASTUS,
    GET_SYSTEM_STASTUS,
    RESET

} Command_t;

typedef enum
{
    IDLE = 1,
    LOCKED,
    LOCK_POS,
    LOCK_ANCHOR_POS,
    UNLOCK,
    REMOTE,
    DOC,
    SAIL
} Status_t;

#endif /* COMMANDS_H_ */