; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:robo-esp-v3]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -D VERSION=Robobuoy_V3.0
    -D ROBOBUOY_V3

monitor_speed = 115200
monitor_port = COM41
# upload_speed = 921600
# upload_port = COM51
board_build.filesystem = littlefs
upload_protocol = espota
#upload_port = 192.168.1.101
upload_port = 192.168.137.102


debug_tool = esp-prog
debug_init_break = tbreak setup

lib_extra_dirs =
    ../RoboDependency

lib_deps =
    RoboCompute
    RoboTone
    br3ttb/PID@^1.2.1
    https://github.com/madhephaestus/ESP32Servo.git
    FastLED/FastLED@3.6.0
    https://github.com/tzapu/WiFiManager
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
    arduino-libraries/Madgwick@^1.2.0
    pololu/LSM303
    links2004/WebSockets@^2.7.3
    bblanchon/ArduinoJson@^7.0.4
