; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:robo-esp-v2]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -D VERSION=Robobuoy_V2.0
    -D ROBOBUOY_V2

monitor_speed = 115200
monitor_port = COM40
upload_speed = 2000000
upload_protocol = esptool

debug_tool = esp-prog
debug_init_break = tbreak setup

lib_extra_dirs =
    ../RoboDependency

lib_deps =
    RoboCompute
    RoboTone
    br3ttb/PID@^1.2.1
    https://github.com/adafruit/Adafruit_LIS2MDL.git
    adafruit/Adafruit LIS2MDL @ ^2.1.8
    https://github.com/adafruit/Adafruit_LSM303_Accel.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/madhephaestus/ESP32Servo.git
    https://github.com/FastLED/FastLED.git
    https://github.com/tzapu/WiFiManager
    https://github.com/adafruit/Adafruit_ICM20X.git
    https://github.com/adafruit/Adafruit_BusIO.git

[env:robo-esp-v3]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -D VERSION=Robobuoy_V3.0
    -D ROBOBUOY_V3

monitor_speed = 115200
monitor_port = COM40
upload_speed = 2000000
upload_protocol = esptool

debug_tool = esp-prog
debug_init_break = tbreak setup

lib_extra_dirs =
    ../RoboDependency

lib_deps =
    RoboCompute
    RoboTone
    br3ttb/PID@^1.2.1
    https://github.com/adafruit/Adafruit_LIS2MDL.git
    adafruit/Adafruit LIS2MDL @ ^2.1.8
    https://github.com/adafruit/Adafruit_LSM303_Accel.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/madhephaestus/ESP32Servo.git
    https://github.com/FastLED/FastLED.git
    https://github.com/tzapu/WiFiManager
    https://github.com/adafruit/Adafruit_ICM20X.git
    https://github.com/adafruit/Adafruit_BusIO.git
