M48
; DRILL file {KiCad 7.0.6} date Sun Aug 13 13:48:50 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-13T13:48:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.461Y-1.9937
X2.461Y-3.9425
T2
X1.9492Y-1.5902
X1.9492Y-4.3461
X5.4925Y-1.5902
X5.4925Y-4.3461
T0
M30
